# Generated by Django 5.0.4 on 2024-05-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_formofpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='road',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
