# Generated by Django 5.0.4 on 2024-05-09 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_address_road'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='road',
            new_name='number',
        ),
    ]
