# Generated by Django 5.0.4 on 2024-05-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_rename_road_address_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=2),
        ),
    ]
