# Generated by Django 5.0.4 on 2024-05-13 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_alter_address_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='rg',
        ),
    ]
