# Generated by Django 5.0.4 on 2024-05-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_remove_person_rg'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='name_mother',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
