# Generated by Django 5.0.4 on 2024-05-30 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_employeestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='employee_status', to='employees.employeestatus'),
        ),
    ]
