# Generated by Django 5.0.4 on 2024-05-31 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_person_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formofpayment',
            name='recipient_name',
        ),
    ]
