# Generated by Django 5.0.4 on 2024-06-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_address_neighborhood'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
